stages:
  - "build"

build-linux:
  stage: "build"
  needs: []
  tags:
    - "linux"
  image: "conanio/clang10:1.54.0"
  before_script:
    # Install the system dependencies for the following conan packages:
    # - https://github.com/conan-io/conan-center-index/blob/master/recipes/egl/system/conanfile.py
    # - https://github.com/conan-io/conan-center-index/blob/master/recipes/opengl/all/conanfile.py
    # - https://github.com/conan-io/conan-center-index/blob/master/recipes/xkeyboard-config/all/conanfile.py
    # - https://github.com/conan-io/conan-center-index/blob/master/recipes/xorg/all/conanfile.py
    # - https://github.com/conan-io/conan-center-index/blob/master/recipes/glu/all/conanfile.py
    - "sudo apt -qq update && sudo apt -qq install -y --no-install-recommends --no-install-suggests -o=Dpkg::Use-Pty=0 libegl1-mesa-dev libgl-dev xkb-data libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-util0-dev libglu1-mesa-dev"
  script:
    - "conan profile new default --detect"
    - "conan install . -s build_type=Release --build missing --install-folder=build -pr:b default -pr:h default -c tools.system.package_manager:mode=install"
    - "cmake -B build -S ."
    - "cmake --build build"
    - "mv ./build/bin/frutibandas ./frutibandas"
  artifacts:
    paths:
      - "frutibandas"

build-mac:
  stage: "build"
  needs: []
  image: macos-12-xcode-13
  tags:
    - "shared-macos-amd64"
  before_script:
    - "brew --version"
    - "brew install cmake conan"
    - "conan --version"
  script:
    - "conan profile new default --detect"
    - "conan install . -s build_type=Release --build missing --install-folder=build -pr:b default -pr:h default -c tools.system.package_manager:mode=install"
    - "cmake -B build -S ."
    - "cmake --build build"
    - "mv ./build/bin/frutibandas ./frutibandas"
  artifacts:
    paths:
      - "frutibandas"
