stages:
  - "build"

build-mac:
  stage: "build"
  needs: []
  tags:
    - "shared-macos-amd64"
  image: "macos-12-xcode-13"
  script:
    - "brew install cmake"
    - "brew install conan"
    - "conan install . -s build_type=Release --build missing --install-folder=build"
    - "cmake -B build -S ."
    - "cmake --build build"
    - "mv ./build/bin/frutibandas"
  artifacts:
    paths:
      - "frutibandas.dmg"
